### PR TITLE
Adds blueprint to simplify the installation of the resolver

### PR DESCRIPTION
**Pull request by MiguelMadero**

### CODE REVIEW

**Comment by toranb** [comment]
@MiguelMadero ah so w/ this in place you won't or don't need to do anything w/ the app/resolver.js file anymore?

**Comment by toranb** [comment]
So after we merge this we could likely publish a v0.0.1 or something that would be much easier /pain free to get started with?

**Comment by MiguelMadero** [comment]
Yes. I publishes 0.0.0

**Comment by toranb** [comment]
I could merge this tonight and publish the v0.0.1 if you add me to npm as an owner :)

`npm owner add toranb ember-cli-hot-loader`

**Comment by MiguelMadero** [comment]
Done.

**Pull request merged**
