### PR TITLE
[BUILD]: updated for ember-getowner-polyfill

### PR DESCRIPTION
**Pull request by toranb**
Updating this to remove dep warning introduced recently

### CODE REVIEW

**Comment by toranb** [comment]
https://github.com/rwjblue/ember-getowner-polyfill/commit/b46db82dd445b5cd4c596abd020df9d7c500c85a

**Comment by toranb** [comment]
@MiguelMadero ping :)

**Comment by MiguelMadero** [comment]
LGTM

**Comment by MiguelMadero** [comment]
Sorry for the delay. I missed the initial email.

**Pull request merged**
