### PR TITLE
Ability to define "shouldExcludeComponent" method in resolver

### PR DESCRIPTION
**Pull request by lifeart**

### CODE REVIEW

**Comment by toranb** [comment]
You'll have to help me out here :) why do we need this extension point if you can already exclude with configuration today? No comment or docs about how/ why anyone would use this so I'm having to assume a good deal at the moment ...

**Comment by lifeart** [comment]
@toranb - main idea is - to have function hook to decide include or exclude component from hot-loading.

At this time -  we can configure component exclusion only by name, but, if I have alot of components to exlude, from bootstrap (for example) or from some UI library - I have this options:

* put all components names into environment config
* ask about ability to add regexp into environment config

But, if I need to exclude components with some more complex logic (by route, by server response, from engine), I need points to control it. And in current implementation this points does not exists.

We can't specify regex or function in environment.js (we must return simple object)

**Comment by toranb** [comment]
@lifeart a summary describing `how-to` use this new feature in the README would be helpful for sure

**Comment by lifeart** [comment]
@toranb done

**Comment by toranb** [comment]
Excellent! Could you also create a sample ember app using this extension point (with bootstrap for example) so the README can make reference to it?

**Comment by lifeart** [comment]
Updated

**Comment by toranb** [comment]
@lifeart  Thanks again for the great work here! I've published this on npm and it's available now using v1.3.0

**Pull request merged**
