### PR TITLE
Adds travis badge to the README

### PR DESCRIPTION
**Pull request by MiguelMadero**
Can you enable travis before merging this? 

Now that we're adding more tests I would like to make sure we have this setup and we keep and green master.

### CODE REVIEW

**Comment by toranb** [comment]
I just got travis unlocked for this repo :)

**Comment by MiguelMadero** [comment]
Cool, can you merge this PR?

**Comment by toranb** [comment]
yessir - also doing a publish in just a sec w/ a new version on npm so I can do some local testing

**Comment by toranb** [comment]
just published v0.0.2 and it's solid my friend :) using it now for some hype video production

**Comment by toranb** [comment]
@MiguelMadero if I haven't said it - your awesome and I feel humbled to even have my name on the list here :)

**Pull request merged**
