### PR TITLE
Fixes action handling

### PR DESCRIPTION
**Pull request by MiguelMadero**
Fixes https://github.com/toranb/ember-cli-hot-loader/issues/27

### CODE REVIEW

**Comment by MiguelMadero** [comment]
targetObject was private in 2.7 and looks like it was removed either in 2.8 or 2.9. Travis failed for 2.9, beta and canary and I verified locally that 2.9.1 doesn't work. I'll leave the PR and this branch in case someone has some time to find an alternative or if the branch helps for someone working in an old version of Ember. I'll focus on the AST branch next week.

**Comment by MiguelMadero** [comment]
I made some good progress on the AST branch. I'll pull the tests for actions from this PR to make sure it works on https://github.com/toranb/ember-cli-hot-loader/pull/25

**Comment by MiguelMadero** [comment]
Retriggering builds. This was the previous status before some upstream changes in Ember: 

image

**Comment by MiguelMadero** [comment]
@oligriffiths just rebased and triggered a new build to see if it makes any difference with the latest versions. I'm not sure if the previous run had the fix for https://github.com/emberjs/ember.js/issues/14168 already

**Comment by MiguelMadero** [comment]
@oligriffiths the tests passed, but we would have to manually verify that it actually hot-reloads since we don't have end to end test automation yet :( 
Can you have a look? Otherwise I could give it a shot early next week.

**Comment by MiguelMadero** [comment]
> Can you have a look? Otherwise I could give it a shot early next week.

And early next week, just became early next month :) I'm having a look now

**Comment by oligriffiths** [comment]
@MiguelMadero awesome, watching intently

**Comment by MiguelMadero** [comment]
Verified manually in 2.7.3, ember-1.13 and ember-release. We're good to merge, sorry for the delay on this.

**Comment by MiguelMadero** [comment]
Released as v0.1.8

**Pull request merged**
