### PR TITLE
Updates the live reload plugin to use the rootURL if available

### PR DESCRIPTION
**Pull request by MiguelMadero**

### CODE REVIEW

**Comment by toranb** [comment]
@MiguelMadero is it possible to test this w/ the dummy app? just curious as we are starting to really build up the "hype" and I'd like to start being more strict w/ PRs if possible (working on a helpers hot reload feature myself and thinking about regression support off the top feels good)

**Comment by MiguelMadero** [comment]
Argh... sorry good catch. I just updated this to work well with the dummy app. 

Also, I completely agree that we should be careful with not breaking things. We need to make a strong effort to add good end to end testing (as mentioned on https://github.com/toranb/ember-cli-hot-loader/issues/7). I looked at a few examples that might help as a starting point, but it's not super simple. Let' follow up there with more details. 

This PR was now manually tested on the dummy app as well as an app with and without rootURL. The lack of test automation shouldn't be a blocker, but it'll certainly slow down our progress since the test matrix is getting more and more complex.

**Comment by toranb** [comment]
@MiguelMadero right on. I left that comment mostly because I started to see the explosion of edge cases and I'm fearful we will soon lose track of them all :)

If this is a legit PR we should merge it/ tag it / npm publish it (feel free if/and when you have time)

**Comment by MiguelMadero** [comment]
Yes, that's pretty similar to what I had, but ran out of batter and didn't get a chance to push it. The new component and the acceptance test will catch this type of issues. This will help us catch issues even after we move to AST. We still need to look at automate the E2E scenario, including actually changing files.

**Comment by MiguelMadero** [comment]
Released as 0.1.3

**Pull request merged**
