### PR TITLE
require.resolve fallback

### LINKED ISSUE #88: Don't work with yarn workspaces
Don't work with [yarn workspaces](https://yarnpkg.com/en/docs/workspaces):
```
=================================================================================
ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/ember-app/tmp/node_modules/ember-source/dist/ember-template-compiler.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SourceMap.addFile (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/fast-sourcemap-concat/lib/source-map.js:77:33)
    at headerFiles.forEach.file (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/broccoli-concat/concat.js:201:18)
    at Array.forEach (<anonymous>)
    at Concat.concat.end.concat (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/broccoli-concat/concat.js:199:26)
    at /home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/fast-sourcemap-concat/lib/source-map.js:431:14
    at new Promise (<anonymous>)
    at SourceMap.end (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/fast-sourcemap-concat/lib/source-map.js:418:12)
    at Concat._doLegacyBuild (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/broccoli-concat/concat.js:184:24)
  - codeFrame: ENOENT: no such file or directory, open '/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/ember-app/tmp/node_modules/ember-source/dist/ember-template-compiler.js'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `SourceMapConcat` plugin. 💥
ENOENT: no such file or directory, open '/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/ember-app/tmp/node_modules/ember-source/dist/ember-template-compiler.js'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `SourceMapConcat` plugin. 💥
ENOENT: no such file or directory, open '/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/ember-app/tmp/node_modules/ember-source/dist/ember-template-compiler.js'
  - name: Error
  - nodeAnnotation: Vendor JS
  - nodeName: SourceMapConcat
  - originalErrorMessage: ENOENT: no such file or directory, open '/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/ember-app/tmp/node_modules/ember-source/dist/ember-template-compiler.js'
  - stack: Error: ENOENT: no such file or directory, open '/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/ember-app/tmp/node_modules/ember-source/dist/ember-template-compiler.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SourceMap.addFile (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/fast-sourcemap-concat/lib/source-map.js:77:33)
    at headerFiles.forEach.file (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/broccoli-concat/concat.js:201:18)
    at Array.forEach (<anonymous>)
    at Concat.concat.end.concat (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/broccoli-concat/concat.js:199:26)
    at /home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/fast-sourcemap-concat/lib/source-map.js:431:14
    at new Promise (<anonymous>)
    at SourceMap.end (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/fast-sourcemap-concat/lib/source-map.js:418:12)
    at Concat._doLegacyBuild (/home/sham/work/ember-cli-hot-loader-with-yarn-worspaces/node_modules/broccoli-concat/concat.js:184:24)

=================================================================================
```
[Repo](https://github.com/shamcode/ember-cli-hot-loader-with-yarn-worspaces/tree/master) for reproduce.

### PR DESCRIPTION
**Pull request by shamcode**
PR fo fix #88

### CODE REVIEW

**Comment by toranb** [comment]
@shamcode is it possible we can try `path.relative(app.project.root, require.resolve())` first, then fallback to a simple `require.resolve` if the compiler is not truly available? I ask because back in July I heard from a few community members who bumped into a problem using `require.resolve` from their mono repo so we altered it and it solved a problem for those developers at the time

https://github.com/toranb/ember-cli-hot-loader/commit/fb0a91124d200480d62af5c164e03ab62a19d162

**Comment by shamcode** [comment]
@toranb, this changed PR, now `require.resolve` works like a fallback. I think that this is exactly what is described in [this](https://github.com/toranb/ember-cli-hot-loader/issues/78#issuecomment-402527025) comment and that ember-cli do when call [`app.import`](https://github.com/ember-cli/ember-cli/blob/6d1fcb5f822db01be1d83a12cca11d8d2091689f/lib/broccoli/ember-app.js#L1477)

**Comment by toranb** [comment]
One issue I found testing this manually with a bigger mono repo just now

```js
    var npmCompilerPath = path.join('ember-source', 'dist', 'ember-template-compiler.js');
    var resolvedPath = require.resolve(npmCompilerPath);
    var npmPath = path.relative(this.project.root, resolvedPath);
```

The `npmPath` returns `../node_modules/ember-source/dist/ember-template-compiler.js` because the node_modules directory is a symlink (pointing back to the parent folder to reuse/share node_modules installed at the top most level of the mono repo). I'm curious if you can think of any way to solve this given I've got a local `node_modules` folder... yet I get the `../node_modules` path

**Comment by shamcode** [comment]
Perhaps the solution will be to add the addon options `templateCompilerPath`, which will be used as the path to the `ember-template-compiler.js`. If this option is not specified, then use the default approach:
```js
path.relative(app.project.root, require.resolve(npmCompilerPath));
```
 Adding this option will preserve backward compatibility and add the ability to use this awesome addon in other specific environments.
What do you think about it?

**Comment by toranb** [comment]
ah I'm digging it actually - so configure it if you need to override the default sorta thing. Where would you override this exactly? command line, config env or something else altogether ?

**Comment by shamcode** [comment]
I think config env will be more familiar to the community. For example, like this:
```js
//my-app/config/environment.js
ENV['ember-cli-hot-loader'] = {
  templateCompilerPath: require.resolve('ember-source/dist/ember-template-compiler.js')
}
```

**Comment by toranb** [comment]
@shamcode I'm down for that - you willing to update the PR in that case? I can test it manually in a few apps I know work today to emsure backwards compat

**Comment by shamcode** [comment]
PR updated

**Comment by toranb** [comment]
Awesome! I'll give this a look later today! Thanks again

**Comment by toranb** [comment]
@shamcode I had success using this in a mono repo (with the configuration below) and for existing hot reload apps I tested it was backwards compatible :)

I've published this on npm and it's available now using v1.2.0

```js
  if (environment === 'development') {
    ENV['ember-cli-hot-loader'] = {
      templateCompilerPath: 'node_modules/ember-source/dist/ember-template-compiler.js'
    }
  }
```

I'll expand the README later next week to include an example for others to better grok this extension point. Thanks again for taking the time to unlock this configuration option!

**Pull request merged**
